### ISSUE TITLE
Regarding use of IndexedDB

### ISSUE THREAD

**Issue by deepraj1729** [rohitmadrileno15/Keep-Notes-PWA#1]
What's the capacity that indexedDB can hold?
Is it really effective for storing relational data?
And finally, what are the browsers that indexedDB supports?

@rohitmadrileno15

**Comment by rohitmadrileno15** [comment]
Okay. So, Indexdb is based totally on your browser and can store data as much as your browser in the machine.
Secondly,  Indexdb is not actually a SQL based database, rather it's a no-SQL based one, storing in key-value pairs. Though, I believe you can build a SQL like DB on top of it.
Thirdly, the browser support for IndexDb is quite good, it's supported by most of the commonly known browsers like , Firefox, Chrome, Safari, and any other browser built on top of Chromium.

**Comment by deepraj1729** [comment]
Thanks @rohitmadrileno15 , that cleared up a lot of doubts.

So, basically it stores data in the Browser's local storage.
Browser's local storage is limited upto 10 MB usually.

**Comment by rohitmadrileno15** [comment]
Okay. They are actually not the same.  I mean, if you compare local storage and Indexdb, they are not the same actually. What I know is, compared to local storage, indexedDb is made for storing a larger amount of data and larger types even.
